env:
  global:
    - CODECOV_TOKEN=:2dbea6dd-502c-4477-a88b-96dfc40f2ed5
language: java
jdk:
  - oraclejdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)